# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b680021051d439939e95973418b3122940261a137897b98f2bf3c08706fc8ac996901cea6dd49c4f72ad71229aafb0c8585bc61732151b2a216ddc7cc2665bb

test:
  secret_key_base: 2333780d213a163a1cc9199e002c04eb0d18e5c1cef6b6d1116642c1f460b4a8e27f16bf30ccb3e481a2e9430e5f6b6a678cd6694d8e6fa72ce2ec61f4724ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
